version: '3'

volumes:
  mongo_dbdata:
  user_data:
  backup_volume:
  cache_volume:
  mongo_backup:

services:
  vms:
    image: pietropietro/volunteers-nowhere:latest
    restart: unless-stopped
    links:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb/volunteers
      - ROOT_URL=http://localhost:3000
      - DELAY=4
      - NODE_ENV=production
    volumes:
      - user_data:/app/programs/server/profilePictures
    links:
      - mongodb
    ports:
      - 3000:80

  mongodb:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    restart: unless-stopped
    volumes:
      - mongo_dbdata:/data/db
